# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-02 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0002_auto_20180802_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
