# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-14 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0002_auto_20180813_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
    ]
