# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-29 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyprofile', '0005_company_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='company/'),
        ),
    ]
